service: createUser

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  # timeout: 10
  stage: dev
  region: ap-east-2

functions:
  api:
    handler: index.handler
    events:
      - http: ANY {proxy+}
      - http: ANY /
